// TODO Add tests for broken up parsing functions

// const cases = [
//   { inputs: [['1']], expected: ['1'] },
//   { inputs: [['1', '2']], expected: ['12'] },
//   { inputs: [['1', '2', '+', '1', '2']], expected: ['12', '+', '12'] },
//   {
//     inputs: [['1', '2', '3', '+', '1', '2', '3', '+', '1', '2', '3']],
//     expected: ['123', '+', '123', '+', '123'],
//   },
//   { inputs: [['1', '2', '.', '1', '2']], expected: ['12.12'] },
//   { inputs: [['.', '1']], expected: ['0.1'] },
//   { inputs: [['.', '1', '+', '.', '1']], expected: ['0.1', '+', '0.1'] },
//   { inputs: [[]], expected: 0 },
//   { inputs: [['1']], expected: 1 },
//   { inputs: [['1', '+', '2']], expected: 3 },
//   { inputs: [['1', '-', '2']], expected: -1 },
//   { inputs: [['1', '+', '2', '+', '3']], expected: 6 },
//   { inputs: [['1', '+', '-', '2']], expected: -1 },
//   { inputs: [['1', 'x', '2']], expected: 2 },
//   { inputs: [['1', 'x', '-', '2']], expected: -2 },
//   { inputs: [['1', 'x', '2', '+', '3', 'x', '4']], expected: 14 },
//   { inputs: [['1', 'x', '2', '-', '3', 'x', '4']], expected: -10 },
//   { inputs: [['1', 'x', '+', '2']], expected: 2 },
//   { inputs: [['+', '1']], expected: 1 },
//   { inputs: [['-', '1']], expected: -1 },
//   { inputs: [['.', '1']], expected: -1 },
//   { inputs: [['0.5']], expected: 0.5 },
//   { inputs: [['√', '4']], expected: 2 },
//   { inputs: [['5', '√', '4']], expected: 10 },
//   { inputs: [['1', '+', '√', '4']], expected: 3 },
//   { inputs: [['1', 'x', '√', '4']], expected: 2 },
//   { inputs: [['1', 'pow', '2']], expected: 1 },
//   { inputs: [['1', 'pow', '0.5']], expected: 1 },
//   { inputs: [['4', 'pow', '0.5']], expected: 2 },
//   { inputs: [['2', 'pow', '-', '1']], expected: 0.5 },
//   { inputs: [['1', 'mod', '2']], expected: 1 },
//   { inputs: [['2', 'mod', '2']], expected: 0 },
//   { inputs: [['3', 'mod', '2']], expected: 1 },
// ];
