name: Publish

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set the release version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV

      - name: Build the image
        run: docker build . -t joellefkowitz/calculator:${{ env.RELEASE_VERSION }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: joellefkowitz
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: joellefkowitz/calculator:${{ env.RELEASE_VERSION }}
